_target_: src.models.aggregations.inverse_forward_ppo.InverseForwardPPO

inverse_dynamics:
  _target_: src.models.inverse_dynamics_lit_module.InverseDynamicsLitModule

  inverse_dynamics_net:
    _target_: src.models.components.inverse_dynamics.inverse_dynamics.InverseDynamics

    observation_encoder:
      _target_: src.models.components.small_conv_net.SmallConvNet
      height: 256 #${environment.sensor.height}
      width: 256 #${environment.sensor.width}
      channels: 3
      dim_out: 1024

    action_predictor:
      _target_: src.models.components.action_predictor.continuous_action_predictor.ContinuousActionPredictor
      dim_embed: ${..observation_encoder.dim_out}
      dim_action: 3

  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 1e-4 # https://github.com/openai/large-scale-curiosity/blob/e0a698676d19307a095cd4ac1991c4e4e70e56fb/run.py#L178
    betas: [0.9, 0.999]

forward_dynamics:
  _target_:
  _partial_: true

ppo:
  _target_:
